# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christophe Maingard
title: Full Stack Engineer
email: christophe.maingard@epitech.eu
# website: www.github.com/ChristopheMaingard/resume

# Social links
github_username:  ChristopheMaingard
linkedin_username: christophe-maingard-577879181

# About Section
# about_title: About Me
about_profile_image: images/profile-picture.jpg
about_content: | # this will include new lines to allow paragraphs
  I began my carreer as a lumberjack but quickly change to became a Fullstack - backend oriented - developper. I've been working on all the development aspects of a project: infrastructure design, CI-CD, backend, frontend... I'm always happy to learn.
  
  I am looking for new opportunities as a remote Full Stack engineer, mainly in a start-up. I would like to work on a rigorous code base, preferably on a high availability service.
  
  I'm mostly good at javascript/typescript, but am keen to learn less dynamic languages like go/rust.

# Projects Section
# projects_title: Projects

content:
  # Experience Section
  - title: Working Experiences
    layout: list
    content:
      - layout: left
        title: FLITDESK
        link: https://www.flitdesk.com
        sub_title: Fullstack Engineer
        caption: October 2019 - Now
        quote: >
         Flitdesk is an SaaS product to manage the Flex Office and its coworking places.
        description: | # this will include new lines to allow paragraphs
          - I was part of the Fullstack Team, composed by myself and I. I often has been a "joining point" between the backend and frontend team. 
          - As I contributed to develop new features, new services, fix bugs and sharing my opinions with the team to take decisions about improving our app.
          - I helped migrating from legacy code to a more modern and suitable framework and distributed architecture to fits our current customers needs, using better practices and clean code.
          - I helped migrating our codebase from Heroku to Google Cloud Platform, which has been an occasion to build a new infrastructure.
          - Facing performances issues, I designed an infrastructure and a codebase to greatly reduce the impact on our legacy API. 
          - In two years, we managed to reduce our APIs response time by 75%, at least.
          - We switched our management from SCRUM to a custom Shape Up in early 2021.
          - Some technologies I use are: Node.js, NestJS, Next.js, Loopback, GraphQL, Javascript, Typescript, Angular, Ionic, Stripe API, Google API, Outlook API, GCP, MongoDB, Terraform.
      - layout: left
        title: Davidson>Transpole
        sub_title: Frontend Developper - Student Developer
        caption: October 2018 - July 2019
        quote: >
          Transpole is Lille's transport company. I was part of a two people frontend development team.
        description: | # this will include new lines to allow paragraphs
          - I have developed frontend interfaces for transpole's internal information system.
          - I have used the redux design pattern to make interactive applications.
          - Some technologies I used were: Angular, RXJS, express.
      - layout: left
        title: Davidson>Life Trophy
        sub_title: Frontend Developper - Student Developer
        caption: March 2016 - October 2018
        quote: >
          Life Trophy is a social network that aims to challenge your friends and gain trophies. This experience was my first developer experience.
        description: | # this will include new lines to allow paragraphs
          - I have been in charge of the development of an hybrid application and its backend.
          - I first started working with a team of 3 persons and ended up beeing the only member of the development team.
          - Life Trophy has been my first experience as a Fullstack Engineer.
          - Some technologies I used were: Angular, Ionic, SpringBoot, Java, Typescript, Travis-ci, PostgresSQL.
      - layout: left
        title: Chantilly Castle
        sub_title: Lumberjack
        caption: 2016 - 2016
        quote: >
          I did this work as a break from my studies
        description: | # this will include new lines to allow paragraphs
          - I mostly cut trees, chop down trees, and plant trees.
          - Some technologies I used were: .

  # Education Section
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Master in IT methods applied to business management
        caption: September 2017 - July 2019
        sub_title: Miage, Lille

      - layout: top-middle
        title: IT Bachelor Degree
        caption: September 2016 - July 2017
        sub_title: CNAM, Amiens

      - layout: top-middle
        title: Two completed years
        caption: October 2011, October 2013
        sub_title: EPITECH, PARIS


  # More Section
  - title: Less professional things you might want to know
    layout: text
    content: |
      Languages
      - French - native language
      - English - B2 (TEOIC: 960 points)
      
      When I'm not learning anything, I like to:
      - Rock climb
      - Treck
      - Read dystopian books - Ask me about titles!
      - Repair motorcycles
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
